-- ALB PostgreSQL initial schema. Hibernate must validate, not create, this schema.
CREATE TABLE media (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP(6),
  updated_at TIMESTAMP(6),
  file_name VARCHAR(255) NOT NULL,
  file_path VARCHAR(255) NOT NULL UNIQUE,
  content_type VARCHAR(255),
  size BIGINT
);

CREATE TABLE news (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP(6),
  updated_at TIMESTAMP(6),
  title VARCHAR(150) NOT NULL,
  subtitle VARCHAR(350),
  content TEXT NOT NULL,
  image_id BIGINT REFERENCES media(id),
  published BOOLEAN
);

CREATE TABLE events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP(6),
  updated_at TIMESTAMP(6),
  title VARCHAR(255) NOT NULL,
  description TEXT,
  start_date DATE,
  end_date DATE,
  location VARCHAR(255),
  image_id BIGINT REFERENCES media(id),
  published BOOLEAN
);

CREATE TABLE pages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP(6),
  updated_at TIMESTAMP(6),
  slug VARCHAR(255) NOT NULL UNIQUE,
  title VARCHAR(255) NOT NULL,
  content TEXT NOT NULL,
  image_id BIGINT REFERENCES media(id)
);

CREATE TABLE partners (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP(6),
  updated_at TIMESTAMP(6),
  name VARCHAR(255),
  type VARCHAR(255),
  website_url VARCHAR(255),
  image_id BIGINT REFERENCES media(id),
  display_order INTEGER
);

CREATE TABLE banner_images (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP(6),
  updated_at TIMESTAMP(6),
  title VARCHAR(255),
  description TEXT,
  image_id BIGINT REFERENCES media(id),
  display_order INTEGER,
  active BOOLEAN
);

CREATE TABLE team_members (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP(6),
  updated_at TIMESTAMP(6),
  first_name VARCHAR(255),
  last_name VARCHAR(255),
  role VARCHAR(255),
  bio TEXT,
  display_order INTEGER
);

CREATE INDEX idx_news_image_id ON news(image_id);
CREATE INDEX idx_events_image_id ON events(image_id);
CREATE INDEX idx_pages_image_id ON pages(image_id);
CREATE INDEX idx_partners_image_id ON partners(image_id);
CREATE INDEX idx_banner_images_image_id ON banner_images(image_id);
